server:
  port: 8080

spring:
  profiles:
    active: dev

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-128
  is-log: true


