#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: # http://127.0.0.1:9000
  accessKey: # admin
  secretKey: #
